// Generated by tools/export_composites_web.py — do not edit by hand.
//
// Every number here is read out of aiur.composites. Regenerate with:
//   python tools/export_composites_web.py
// tests/test_composites_web_export.py fails if this file is stale.

export const COMPOSITES = {
  "gate": {
    "valid": true,
    "errorCount": 0,
    "criticalFailureCount": 0
  },
  "evidence": {
    "measuredAllowables": 0,
    "plannedCoupons": 70,
    "statement": "This program holds no measured allowables. Every laminate schedule is sized against handbook-representative lamina values and is therefore a design study, not a design. The coupon plan below is what converts it."
  },
  "parts": [
    {
      "id": "CS-100",
      "name": "capture throat cup",
      "stack": "[45/45/0]s",
      "thicknessMm": 0.414,
      "arealMassGsm": 664.7,
      "partMassG": 7.75,
      "quantity": 1,
      "sizedBy": "Handling load, then the fibre drift a cone imposes"
    },
    {
      "id": "CS-200",
      "name": "deployable capture-ring boom",
      "stack": "[45]s (PW-C-80)",
      "thicknessMm": 0.16,
      "arealMassGsm": 248.5,
      "partMassG": 26.24,
      "quantity": 12,
      "sizedBy": "Stowed strain at its packing radius"
    },
    {
      "id": "CS-300",
      "name": "keel rail web",
      "stack": "[45/0/0/0]s",
      "thicknessMm": 1.356,
      "arealMassGsm": 2112.7,
      "partMassG": 42.25,
      "quantity": 1,
      "sizedBy": "Axial stiffness, then cooldown residual stress"
    },
    {
      "id": "CS-400",
      "name": "keeper tine",
      "stack": "[45/0/0/45]s (PW-C-193)",
      "thicknessMm": 1.592,
      "arealMassGsm": 2458.0,
      "partMassG": 5.9,
      "quantity": 2,
      "sizedBy": "Retention-ledge geometry, not retention load"
    }
  ],
  "findings": [
    {
      "id": "01",
      "title": "The funnel stopped being a laminate",
      "figure": "789 g/m²",
      "copy": "A monolithic funnel skin able to carry the handling load across the boom pitch weighs 54 g — a third of the entire dock mass allocation, for a part whose only job is to guide an aircraft. It became a tensioned membrane between the deployable booms, and the laminate content retreated to the throat cup."
    },
    {
      "id": "02",
      "title": "Cooldown chose the keel rail's material",
      "figure": "0.56",
      "copy": "The obvious rail — high-modulus tape at 0/90, and 20 g lighter — is predicted to microcrack on the tool from residual stress alone, before it ever sees a load. The rail that shipped uses intermediate-modulus tape with fabric carrying the transverse direction and closes at 1.41."
    },
    {
      "id": "03",
      "title": "A cone will not hold a fibre angle",
      "figure": "255°",
      "copy": "Develop a cone flat and its meridians become radial lines, so a straight fibre's angle to them drifts one degree per degree of sector. Holding ±3° would take 43 gores. The throat cup is built in-plane isotropic instead: its predecessor varied 47 % in axial stiffness around its own circumference, and this stack varies 7 %."
    },
    {
      "id": "04",
      "title": "Full cure is unreachable at the cure temperature",
      "figure": "199 °C",
      "copy": "The resin's kinetics impose a conversion ceiling that rises with hold temperature — about 0.86 at 180 °C however long it is held. So cure acceptance is completeness against that ceiling, which catches a hold that is too short, plus glass-transition margin, which catches one that is too cold."
    },
    {
      "id": "05",
      "title": "A bond cannot always be designed to fail its adherend",
      "figure": "4.8 mm",
      "copy": "The standard rule for an unverifiable bond is to out-strength what it joins. Achievable for a thin adherend and arithmetically impossible for a thick one — the keeper tine would need that bondline. So there are two qualification routes, and the second — load margin plus a proof test on every article — is always available. The boom root reaches the first at 0.30 mm."
    },
    {
      "id": "06",
      "title": "A shallow delamination is worse than a deep one",
      "figure": "0.8 mm",
      "copy": "The plies above a delamination buckle as a small plate, and one thin ply has almost no bending stiffness. In the throat cup a delamination one ply down is critical at a 0.8 mm radius; the same delamination at mid-thickness tolerates 3.3 mm. The dangerous case is the one hardest to detect, so acceptance limits are depth-dependent."
    },
    {
      "id": "07",
      "title": "A 2° wrinkle costs 42 % of compressive strength",
      "figure": "−42%",
      "copy": "Compressive failure is fibre microbuckling, so an out-of-plane wave adds directly to the misalignment already present. It is why a wrinkle is a structural defect rather than a cosmetic one, and why it cannot be repaired: the fibre is already where it is."
    }
  ],
  "delamination": [
    {
      "id": "CS-100",
      "shallowMm": 0.8,
      "midMm": 3.3
    },
    {
      "id": "CS-300",
      "shallowMm": 6.9,
      "midMm": 23.3
    },
    {
      "id": "CS-400",
      "shallowMm": 8.6,
      "midMm": 30.9
    }
  ],
  "massRollup": [
    {
      "line": "active recovery dock allocation",
      "budgetG": 180.0,
      "allocatedG": 44.5,
      "actualG": 39.89
    },
    {
      "line": "wiring + mounting reserve",
      "budgetG": 100.0,
      "allocatedG": 45.0,
      "actualG": 42.25
    }
  ],
  "modules": [
    {
      "name": "materials",
      "copy": "Lamina and resin properties, each carrying the basis it came from — and what that basis allows it to be used for."
    },
    {
      "name": "clt",
      "copy": "Classical laminate theory: ABD stiffness, thermal and cure-shrinkage response, ply-by-ply failure."
    },
    {
      "name": "schedules",
      "copy": "The four part laminates, their load cases, and the design rules they are checked against."
    },
    {
      "name": "flatpattern",
      "copy": "Flat-pattern development, the fibre drift a cone imposes, and the rotational stiffness envelope."
    },
    {
      "name": "cure",
      "copy": "Cure kinetics, vitrification, exotherm, viscosity, and the pressure window."
    },
    {
      "name": "bonding",
      "copy": "Bonded-joint shear lag, overlap saturation, and the two qualification routes."
    },
    {
      "name": "springin",
      "copy": "Corner distortion prediction and the tool compensation loop."
    },
    {
      "name": "tooling",
      "copy": "Tool material trade and thermal-expansion compensation."
    },
    {
      "name": "process",
      "copy": "Fibre volume fraction, void content, debulk schedule, panel acceptance."
    },
    {
      "name": "disposition",
      "copy": "What a defect costs, and the accept / repair / scrap call."
    },
    {
      "name": "traveler",
      "copy": "Travelers, hold points, prepreg out-time, and computed nonconformances."
    },
    {
      "name": "allowables",
      "copy": "Basis values, the coupon plan, and the cost of scatter."
    },
    {
      "name": "spc",
      "copy": "Process capability, control charts, and rolled throughput yield."
    },
    {
      "name": "doe",
      "copy": "The experiments that replace this package's engineering targets."
    }
  ],
  "experimentRuns": 54
} as const;
