"""The website's structures page must not drift from the models.

The site's own rule is that nothing on it is summarised out of the repository
by hand. A generated data file only keeps that promise while it is current,
so the check that matters here is the staleness one: regenerate, compare, and
fail if the committed module and the models disagree.

The rest of these tests guard the specific ways a published number can go
wrong — a figure quoted in prose that no longer matches the model it came
from, a mass rollup that has stopped agreeing with the schedules, or a page
that has quietly stopped saying the programme holds no measured allowables.
"""

import importlib.util
import json
import re
import unittest
from pathlib import Path

from aiur.composites import allowables, schedules

REPO_ROOT = Path(__file__).resolve().parents[1]
EXPORT = REPO_ROOT / "web" / "lib" / "composites-data.ts"
PAGE = REPO_ROOT / "web" / "app" / "structures" / "page.tsx"


def _load_exporter():
    path = REPO_ROOT / "tools" / "export_composites_web.py"
    spec = importlib.util.spec_from_file_location("export_composites_web", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _payload() -> dict:
    text = EXPORT.read_text(encoding="utf-8")
    body = text[text.index("{") : text.rindex("}") + 1]
    return json.loads(body)


class ExportFreshnessTest(unittest.TestCase):
    def setUp(self):
        self.exporter = _load_exporter()

    def test_committed_export_is_current(self):
        self.assertTrue(EXPORT.exists(), "the site data file is missing")
        self.assertEqual(
            self.exporter.render(self.exporter.build()),
            EXPORT.read_text(encoding="utf-8"),
            "web/lib/composites-data.ts is stale; run "
            "python tools/export_composites_web.py",
        )

    def test_check_mode_agrees(self):
        self.assertEqual(0, self.exporter.main(["--check"]))

    def test_export_is_marked_generated(self):
        head = EXPORT.read_text(encoding="utf-8").splitlines()[0]
        self.assertIn("Generated by", head)
        self.assertIn("do not edit by hand", head)


class PublishedNumbersTest(unittest.TestCase):
    def setUp(self):
        self.data = _payload()

    def test_parts_match_the_schedules(self):
        published = {row["id"]: row for row in self.data["parts"]}
        self.assertEqual({item.part_id for item in schedules.SCHEDULES}, set(published))
        for result in schedules.evaluate_all():
            row = published[result["part_id"]]
            self.assertEqual(result["stack"], row["stack"])
            self.assertEqual(result["thickness_mm"], row["thicknessMm"])
            self.assertEqual(result["areal_mass_g_m2"], row["arealMassGsm"])
            self.assertEqual(result["part_mass_g"], row["partMassG"])

    def test_mass_rollup_matches_the_schedules(self):
        published = {row["line"]: row for row in self.data["massRollup"]}
        for entry in schedules.mass_rollup():
            row = published[entry["budget_line"]]
            self.assertEqual(entry["budget_g"], row["budgetG"])
            self.assertEqual(entry["actual_g"], row["actualG"])

    def test_evidence_state_matches_the_allowables_module(self):
        status = allowables.program_status()
        self.assertEqual(
            status["measured_allowables"], self.data["evidence"]["measuredAllowables"]
        )
        self.assertEqual(
            status["planned_coupons"], self.data["evidence"]["plannedCoupons"]
        )

    def test_the_page_still_says_the_programme_holds_no_allowables(self):
        # The single most important claim on the page, and the one a
        # cheerful edit would remove first.
        self.assertEqual(0, self.data["evidence"]["measuredAllowables"])
        self.assertIn("design study", self.data["evidence"]["statement"])

    def test_gate_state_is_published_honestly(self):
        from aiur.composites.__main__ import snapshot

        report = snapshot()
        self.assertEqual(report["valid"], self.data["gate"]["valid"])
        self.assertEqual(len(report["errors"]), self.data["gate"]["errorCount"])

    def test_every_finding_carries_a_figure_and_copy(self):
        self.assertGreaterEqual(len(self.data["findings"]), 6)
        for finding in self.data["findings"]:
            self.assertTrue(finding["figure"], finding["id"])
            self.assertTrue(finding["title"], finding["id"])
            self.assertGreater(len(finding["copy"]), 80, finding["id"])

    def test_delamination_shallow_limit_is_tighter_than_the_deep_one(self):
        # The published claim of the disposition section. If a laminate
        # change ever inverted this, the page would be asserting something
        # the model no longer supports.
        for row in self.data["delamination"]:
            self.assertLess(row["shallowMm"], row["midMm"], row["id"])

    def test_module_list_matches_the_package(self):
        published = {module["name"] for module in self.data["modules"]}
        package = {
            path.stem
            for path in (REPO_ROOT / "aiur" / "composites").glob("*.py")
            if not path.stem.startswith("__")
        }
        self.assertEqual(package, published)


class PageTest(unittest.TestCase):
    def setUp(self):
        self.source = PAGE.read_text(encoding="utf-8")

    def test_page_reads_from_the_generated_module(self):
        self.assertIn('from "@/lib/composites-data"', self.source)

    def test_page_hard_codes_no_figures_from_the_models(self):
        # Any number the models own must arrive through COMPOSITES. A few
        # editorial constants are allowed, so this checks the specific
        # values that would silently rot: part masses and thicknesses.
        for result in schedules.evaluate_all():
            for value in (result["areal_mass_g_m2"], result["part_mass_g"]):
                self.assertNotIn(
                    str(value), self.source, f"{value} is hard-coded into the page"
                )

    def test_module_links_point_at_the_source(self):
        self.assertIn("blob/main/aiur/composites", self.source)

    def test_page_is_in_the_site_navigation(self):
        content = (REPO_ROOT / "web" / "lib" / "site-content.ts").read_text(
            encoding="utf-8"
        )
        self.assertIn('"/structures"', content)
        # And in the prev/next rail, or the page is unreachable by walking.
        order = content[content.index("PAGE_ORDER") :]
        self.assertIn('["/structures"', re.sub(r"\s+", "", order).replace('",', '",'))


if __name__ == "__main__":
    unittest.main()
